//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NQuery.Authoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NQuery.Authoring.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous Name:.
        /// </summary>
        internal static string AmbiguousName {
            get {
                return ResourceManager.GetString("AmbiguousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;AS&apos; keyword.
        /// </summary>
        internal static string CodeActionAddAsKeyword {
            get {
                return ResourceManager.GetString("CodeActionAddAsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing &apos;{0}&apos; keyword.
        /// </summary>
        internal static string CodeActionAddMissingKeyword {
            get {
                return ResourceManager.GetString("CodeActionAddMissingKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parentheses.
        /// </summary>
        internal static string CodeActionAddParentheses {
            get {
                return ResourceManager.GetString("CodeActionAddParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing RECURSIVE keyword.
        /// </summary>
        internal static string CodeActionAddRecursive {
            get {
                return ResourceManager.GetString("CodeActionAddRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;{0}&apos; to GROUP BY.
        /// </summary>
        internal static string CodeActionAddToGroupBy {
            get {
                return ResourceManager.GetString("CodeActionAddToGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to SELECT list.
        /// </summary>
        internal static string CodeActionAddToSelectList {
            get {
                return ResourceManager.GetString("CodeActionAddToSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to IS NOT NULL.
        /// </summary>
        internal static string CodeActionConvertToIsNotNull {
            get {
                return ResourceManager.GetString("CodeActionConvertToIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to IS NULL.
        /// </summary>
        internal static string CodeActionConvertToIsNull {
            get {
                return ResourceManager.GetString("CodeActionConvertToIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand wildcard.
        /// </summary>
        internal static string CodeActionExpandWildcard {
            get {
                return ResourceManager.GetString("CodeActionExpandWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &apos;{0}&apos; operands.
        /// </summary>
        internal static string CodeActionFlipOperands {
            get {
                return ResourceManager.GetString("CodeActionFlipOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &apos;{0}&apos; operator to &apos;{1}&apos;.
        /// </summary>
        internal static string CodeActionFlipOperatorTo {
            get {
                return ResourceManager.GetString("CodeActionFlipOperatorTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify column.
        /// </summary>
        internal static string CodeActionQualifyColumn {
            get {
                return ResourceManager.GetString("CodeActionQualifyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unnecessary RECURSIVE keyword.
        /// </summary>
        internal static string CodeActionRemoveRecursive {
            get {
                return ResourceManager.GetString("CodeActionRemoveRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant brackets.
        /// </summary>
        internal static string CodeActionRemoveRedundantBrackets {
            get {
                return ResourceManager.GetString("CodeActionRemoveRedundantBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant parenthesis.
        /// </summary>
        internal static string CodeActionRemoveRedundantParenthesis {
            get {
                return ResourceManager.GetString("CodeActionRemoveRedundantParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unnecessary columns from EXISTS.
        /// </summary>
        internal static string CodeActionRemoveUnnecessaryColumnsFromExists {
            get {
                return ResourceManager.GetString("CodeActionRemoveUnnecessaryColumnsFromExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused common table expression.
        /// </summary>
        internal static string CodeActionRemoveUnusedCommonTableExpression {
            get {
                return ResourceManager.GetString("CodeActionRemoveUnusedCommonTableExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace expression by SELECT column reference.
        /// </summary>
        internal static string CodeActionReplaceByNamedColumn {
            get {
                return ResourceManager.GetString("CodeActionReplaceByNamedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace ordinal by named column reference.
        /// </summary>
        internal static string CodeActionReplaceOrdinalByNamedColumn {
            get {
                return ResourceManager.GetString("CodeActionReplaceOrdinalByNamedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with BETWEEN.
        /// </summary>
        internal static string CodeActionReplaceWithBetween {
            get {
                return ResourceManager.GetString("CodeActionReplaceWithBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ascending.
        /// </summary>
        internal static string CodeActionToAscending {
            get {
                return ResourceManager.GetString("CodeActionToAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To descending.
        /// </summary>
        internal static string CodeActionToDescending {
            get {
                return ResourceManager.GetString("CodeActionToDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To explicit sort order.
        /// </summary>
        internal static string CodeActionToExplicitSortOrder {
            get {
                return ResourceManager.GetString("CodeActionToExplicitSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To implicit sort order.
        /// </summary>
        internal static string CodeActionToImplicitSortOrder {
            get {
                return ResourceManager.GetString("CodeActionToImplicitSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison with NULL results in NULL.
        /// </summary>
        internal static string CodeIssueComparsionWithNullIsAlwaysNull {
            get {
                return ResourceManager.GetString("CodeIssueComparsionWithNullIsAlwaysNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is always NULL.
        /// </summary>
        internal static string CodeIssueExpressionIsAlwaysNull {
            get {
                return ResourceManager.GetString("CodeIssueExpressionIsAlwaysNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECURSIVE is not needed.
        /// </summary>
        internal static string CodeIssueRecursiveIsNotNeeded {
            get {
                return ResourceManager.GetString("CodeIssueRecursiveIsNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should specify RECURSIVE.
        /// </summary>
        internal static string CodeIssueShouldSpecifyRecursive {
            get {
                return ResourceManager.GetString("CodeIssueShouldSpecifyRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (+ {1} overload(s)).
        /// </summary>
        internal static string CompletionItemWithOverloads {
            get {
                return ResourceManager.GetString("CompletionItemWithOverloads", resourceCulture);
            }
        }
    }
}
