<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net481</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NQuery.Authoring\NQuery.Authoring.csproj" />
    <ProjectReference Include="..\..\src\NQuery.Testing\NQuery.Testing.csproj" />
    <ProjectReference Include="..\..\src\NQuery\NQuery.csproj" />
  </ItemGroup>

</Project>
