<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net481</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NQuery.Dynamic\NQuery.Dynamic.csproj" />
    <ProjectReference Include="..\NQuery.Testing\NQuery.Testing.csproj" />
    <ProjectReference Include="..\NQuery\NQuery.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <PackageReference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
