<Project>

  <PropertyGroup>
    <Copyright>Copyright (c) Immo Landwerth</Copyright>
    <Company>Immo Landwerth</Company>
    <Product>NQuery</Product>
    <NoWarn>$(NoWarn);NU1701;MSB3277</NoWarn>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)../artifacts</ArtifactsPath>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName) == 'NQueryViewer' OR $(MSBuildProjectName.EndsWith('.Testing'))">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsPackable)' != 'false'">
    <Authors>$(Company)</Authors>
    <RepositoryUrl>https://github.com/terrajobst/nquery-vnext</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageTags>NQuery SQL</PackageTags>
    <Description>$(Product)</Description>
  </PropertyGroup>

</Project>
