<Project>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)\Common\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <None Include="$(MSBuildThisFileDirectory)\xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
