name: CICD

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOTNET_NOLOGO: true
  SLN: ${{ github.workspace }}/src/NQuery.slnx

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # We need the full history in order to use Git versioning
      - name: Get .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.*'
      - name: dotnet build
        run: |
          dotnet build ${env:SLN} -c Release --nologo
      - name: dotnet test
        run: |
          dotnet test ${env:SLN} --nologo
      - name: Upload binaries
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'terrajobst'
        uses: actions/upload-artifact@v7
        with:
          path: artifacts
          name: artifacts
  push-to-github:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'terrajobst'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: artifacts
          path: artifacts
      - run: |
          dotnet nuget push artifacts/package/release/*.nupkg -s "https://nuget.pkg.github.com/terrajobst/index.json" -k ${{ secrets.GITHUB_TOKEN }}
