name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: .\build.cmd
  push-to-myget:
    if: github.event_name == 'push' && github.ref == 'master'
    needs: build
    runs-on: windows-latest
    steps:
    - name: Publish packages
      run: echo Pushing packages
